### PR TITLE
Job Search added

### PR DESCRIPTION
**Pull request by tushar-rishav**

### CODE REVIEW

**Comment by sananth12** [comment]
@tushar-rishav  Please update the README.md too.

**Comment by tushar-rishav** [comment]
@sananth12  Updated!

**Comment by sananth12** [comment]
@tushar-rishav :+1: 
@harshasrinivas Merge after testing locally

**Comment by harshasrinivas** [comment]
@tushar move the function `show_job` to `cli_github/utils.py` file.
And all other requests have been made using `urllib.request` library. Why use `requests` for this alone? So replace `requests` with `urllib.request`

**Comment by tushar-rishav** [comment]
@harshasrinivas  Updated! I ran unit test and it worked fine. You do the same and merge!

**Comment by harshasrinivas** [comment]
many errors @tushar-rishav 
Test it on your machine properly before issuing a pull

**Pull request closed without merging**
