### PR TITLE
conform to pep8 guidelines

### PR DESCRIPTION
**Pull request by SanketDG**
Hey just fixed your code to conform to [pep8](https://www.python.org/dev/peps/pep-0008/).

Thanks!

### CODE REVIEW

**Comment by harshasrinivas** [comment]
make sure that the `__future__ import` lines are placed at the beginning of the file.

**Comment by SanketDG** [comment]
Yeah, ok. Done!

You should turn off Travis CI, you have no tests.

**Comment by harshasrinivas** [comment]
Cool. Just put these two lines on top as well.
`from future.standard_library import install_aliases` 
`install_aliases()`

It is used to make the module `urllib.request` compatible with python 2.x!

**Comment by harshasrinivas** [comment]
And thanks for fixing the typo! :+1:

**Comment by SanketDG** [comment]
> It is used to make the module urllib.request compatible with python 2.x!

Oh! I see. Sorry for that.
btw I removed `from string import *` is that okay?

**Comment by harshasrinivas** [comment]
yes, `string` module is important. it is what is responsible for the `find()` method to work

**Comment by SanketDG** [comment]
Well, have you every tried using `find` without importing `string` module? It works. Every string object by default has these methods, you don't need to import anything for them to work.

**Comment by sananth12** [comment]
@harshasrinivas 
Also, avoid `import *` at all costs.

https://www.python.org/dev/peps/pep-0020/

```
Explicit is better than implicit.
```

**Comment by harshasrinivas** [comment]
yeah thanks @sananth12  ! :+1: 
@SanketDG oh cool, thanks! You can make the remaining changes now :)

**Comment by SanketDG** [comment]
Ready for merge.

**Comment by harshasrinivas** [comment]
Thanks! @SanketDG , you have been added to the list of contributors :sweat_smile:

**Pull request merged**
